name: Build

on:
  workflow_dispatch:

jobs:
  build-v3:
    runs-on: macos-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: latest-stable
      - name: Set variables
        run: |
          HASH=$(cat SNAPSHOT_HASH)
          echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Install tools
        run: |
          brew install ninja libusbmuxd ideviceinstaller ios-deploy # python@3.11
          # sudo rm -rf /usr/local/bin/python3
          # sudo ln -s /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 /usr/local/bin/python3
          # python3 -m pip install wheel
          # python3 -m pip install .
          python3 --version
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          git clone https://github.com/flutter/engine.git
          pip3 install reflutter==0.8.0
          reflutter
      - name: gclient sync
        run: |
          ROOT_DIR=$(pwd)
          export PATH=$PATH:$ROOT_DIR/depot_tools:/Library/Frameworks/Python.framework/Versions/3.13.1/bin
          cd engine
          git config --global user.email "reflutter@example.com" && git config --global user.name "reflutter"
          SNAPSHOT=$(reflutter ${{env.SNAPSHOT_HASH}} -l)
          git fetch origin $SNAPSHOT
          git reset --hard FETCH_HEAD
          reflutter ${{env.SNAPSHOT_HASH}} -l
          echo 'reflutter' > REFLUTTER
          git add . && git commit -am "reflutter"
          cd $ROOT_DIR
          mkdir customEngine
          cd customEngine
          echo 'solutions = [{"managed": False,"name": "src/flutter","url": "'$ROOT_DIR/engine'","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' > .gclient
          gclient sync
          reflutter ${{env.SNAPSHOT_HASH}} -l
      - name: ninja build Flutter.framework
        run: export PATH=$PATH:`pwd`/depot_tools && sudo xcode-select -s /Applications/Xcode.app && customEngine/src/flutter/tools/gn --no-goma --ios --runtime-mode=release && ninja -C customEngine/src/out/ios_release
      - name: Move to release
        run: |
          cp customEngine/src/out/ios_release/Flutter.framework/Flutter Flutter
      - name: iOS-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ios-v3-${{env.SNAPSHOT_HASH}}
          files: |
            ./Flutter

